* =--- Day 5: Alchemical Reduction ---=
You've managed to sneak in to the prototype suit manufacturing lab. The Elves are making decent progress, but are still struggling with the suit's size reduction capabilities.

While the very latest in 1518 alchemical technology might have solved their problem eventually, you can do better. You scan the chemical composition of the suit's material and discover that it is formed by extremely long polymers (one of which is available as your puzzle input).

The polymer is formed by smaller units which, when triggered, react with each other such that two adjacent units of the same type and opposite polarity are destroyed. Units' types are represented by letters; units' polarity is represented by capitalization. For instance, r and R are units with the same type but opposite polarity, whereas r and s are entirely different types and do not react.

For example:

- In aA, a and A react, leaving nothing behind.
- In abBA, bB destroys itself, leaving aA. As above, this then destroys itself, leaving nothing.
- In abAB, no two adjacent units are of the same type, and so nothing happens.
- In aabAAB, even though aa and AA are of the same type, their polarities match, and so nothing happens.

Now, consider a larger example, dabAcCaCBAcCcaDA:

#+BEGIN_SRC 
dabAcCaCBAcCcaDA  The first 'cC' is removed.
dabAaCBAcCcaDA    This creates 'Aa', which is removed.
dabCBAcCcaDA      Either 'cC' or 'Cc' are removed (the result is the same).
dabCBAcaDA        No further actions can be taken.
#+END_SRC

After all possible reactions, the resulting polymer contains 10 units.

How many units remain after fully reacting the polymer you scanned?

** Solution
#+BEGIN_SRC scheme :tangle src/day05/solution1.scm
  #!/usr/bin/guile \
  -e solution1 -s
  !#
  (use-modules (aoc parse)
               (ice-9 regex)
               (srfi srfi-1))

  (define input (car (with-input-from-file "testinput.txt" parse-input)))

  (define (polymers-remaining polymers)
    "Return the number of polymers remaining after reacting,
  e.g. remove all matching 'Aa/aA', and return the length after all have been removed"
    (let ((re "aA|Aa|bB|Bb|cC|Cc|dD|Dd|eE|Ee|fF|Ff|gG|Gg|hH|Hh|iI|Ii|jJ|Jj|kK|Kk|lL|Ll|mM|Mm|nN|Nn|oO|Oo|pP|Pp|qQ|Qq|rR|Rr|sS|Ss|tT|Tt|uU|Uu|vV|Vv|wW|Ww|xX|Xx|yY|Yy|zZ|Zz"))
      (do ((reacted polymers (regexp-substitute/global #f re reacted 'pre "" 'post)))
          ((not (string-match re reacted))
           (string-length reacted)))))

  (define (solution1 args)
    (display (polymers-remaining input)))
#+END_SRC

* =--- Part Two ---=
Time to improve the polymer.

One of the unit types is causing problems; it's preventing the polymer from collapsing as much as it should. Your goal is to figure out which unit type is causing the most problems, remove all instances of it (regardless of polarity), fully react the remaining polymer, and measure its length.

For example, again using the polymer dabAcCaCBAcCcaDA from above:

- Removing all A/a units produces dbcCCBcCcD. Fully reacting this polymer produces dbCBcD, which has length 6.
- Removing all B/b units produces daAcCaCAcCcaDA. Fully reacting this polymer produces daCAcaDA, which has length 8.
- Removing all C/c units produces dabAaBAaDA. Fully reacting this polymer produces daDA, which has length 4.
- Removing all D/d units produces abAcCaCBAcCcaA. Fully reacting this polymer produces abCBAc, which has length 6.

In this example, removing all C/c units was best, producing the answer 4.

What is the length of the shortest polymer you can produce by removing all units of exactly one type and fully reacting the result?

** Solution
Reuse =polymers-remaining= from part 1.

#+BEGIN_SRC scheme :tangle src/day05/solution2.scm
  #!/usr/bin/guile \
  -e solution2 -s
  !#
  (use-modules (aoc parse)
               (ice-9 regex)
               (srfi srfi-1))

  (define input (car (with-input-from-file "input.txt" parse-input)))

  (define (smallest-reaction polymers)
    "Find the shortest polymer you can produce after removing all of a single unit, e.g. A/a"

    (let ((re "aA|Aa|bB|Bb|cC|Cc|dD|Dd|eE|Ee|fF|Ff|gG|Gg|hH|Hh|iI|Ii|jJ|Jj|kK|Kk|lL|Ll|mM|Mm|nN|Nn|oO|Oo|pP|Pp|qQ|Qq|rR|Rr|sS|Ss|tT|Tt|uU|Uu|vV|Vv|wW|Ww|xX|Xx|yY|Yy|zZ|Zz")
          (units (string->list "abcdefghijklmnopqrstuvwxyz")))

      (define (polymers-remaining polymers)
        "Return the number of polymers remaining after reacting,
  e.g. remove all matching 'Aa/aA', and return the length after all have been removed"
        (do ((reacted polymers (regexp-substitute/global #f re polymers 'pre "" 'post)))
            ((not (string-match re reacted))
             (string-length reacted))))

      (define (remove-unit unit polymers)
        "Remove a unit (letter) from polymers"
        (list->string (filter! (lambda (x) (not (char-ci=? x unit))) (string->list polymers))))

      (apply min (map! polymers-remaining (map! (lambda (unit) (remove-unit unit polymers)) units)))))

  (define (solution2 args)
    (display (smallest-reaction input)))
#+END_SRC
